apiVersion: v1
kind: Secret
metadata:
  name: demolabs-db-secret
  namespace: demolabs
type: Opaque
# Values below are base64 of: postgres / demolabs123
# echo -n 'postgres' | base64   -> cG9zdGdyZXM=
# echo -n 'demolabs123' | base64 -> ZGVtb2xhYnMxMjM=
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: ZGVtb2xhYnMxMjM=
