apiVersion: v1
kind: ConfigMap
metadata:
  name: demolabs-db-config
  namespace: demolabs
data:
  POSTGRES_DB: demolabsdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demolabs-backend-config
  namespace: demolabs
data:
  # Points at the Postgres ClusterIP Service by its in-cluster DNS name
  DB_HOST: "demolabs-postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "demolabsdb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demolabs-db-initsql
  namespace: demolabs
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS tasks (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        done BOOLEAN DEFAULT FALSE
    );
    INSERT INTO tasks (title, done) VALUES ('Set up demolabs namespace', TRUE);
